"use client";
import {useEffect,useMemo,useRef,useState,type CSSProperties} from "react";
import {Trophy,Users,UserRound,Settings,Crown,Zap,Timer,Flame,Gamepad2,Check,X,RotateCcw,Lightbulb,Pencil,Eraser,Menu,Coins,ShieldCheck,Swords,CalendarDays,LockKeyhole,Heart} from "lucide-react";
import "./sudoku-grid.css";
import {AccountButton,AccountOverview,AuthDialog,PrivateLobby,RealFriends,Room,RoomPlayer,useAccount} from "./real-account";
import {supabase} from "./lib/supabase";
import {nextSudokuVariant} from "./lib/sudoku-variants";
import {RankedMatch,rankedRequest,RankedState} from "./ranked-match";
import {AvatarShop,PlayerAvatar,useCosmetics} from "./player-cosmetics";
import {gridThemes} from "@/lib/cosmetics";
type View="jouer"|"compte"|"tournois"|"classement"|"amis"|"stats"|"boutique";
type Difficulty="Débutant"|"Facile"|"Intermédiaire"|"Difficile"|"Expert"|"Maître";
type ChallengeData={status:"not_started"|"in_progress"|"completed"|"failed";title:string;puzzle:number[];nextAt:string;startedAt:string|null;elapsedSeconds:number|null;mistakes:number};
const rawPuzzles:Record<Difficulty,string>={Débutant:"534678912672195348198342567859761423426853791713924856961537284287419635345286000",Facile:"530070000600195000098000060800060003400803001700020006060000280000419005000080079",Intermédiaire:"000260701680070090190004500820100040004602900050003028009300074040050036703018000",Difficile:"000000907000420180000705026100904000050000040000507009920108000034059000507000000",Expert:"005300000800000020070010500400005300010070006003200080060500009004000030000009700",Maître:"100007090030020008009600500005300900010080002600004000300000010040000007007000300"};
const toGrid=(s:string)=>s.split("").map(Number);
function solveSudoku(source:number[]){const grid=[...source];const valid=(p:number,n:number)=>{const r=Math.floor(p/9),c=p%9;for(let i=0;i<9;i++)if(grid[r*9+i]===n||grid[i*9+c]===n)return false;const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let y=0;y<3;y++)for(let x=0;x<3;x++)if(grid[(br+y)*9+bc+x]===n)return false;return true};const solve=():boolean=>{let p=-1,best:number[]=[];for(let i=0;i<81;i++)if(!grid[i]){const opts=[];for(let n=1;n<=9;n++)if(valid(i,n))opts.push(n);if(!opts.length)return false;if(p<0||opts.length<best.length){p=i;best=opts;if(opts.length===1)break}}if(p<0)return true;for(const n of best){grid[p]=n;if(solve())return true;grid[p]=0}return false};return solve()?grid:null}
const puzzles=Object.fromEntries(Object.entries(rawPuzzles).map(([difficulty,value])=>{const puzzle=toGrid(value),solution=solveSudoku(puzzle);if(!solution)throw new Error(`Grille invalide: ${difficulty}`);return[difficulty,{puzzle,solution,id:`${difficulty.toLowerCase()}-01`}]})) as Record<Difficulty,{puzzle:number[];solution:number[];id:string}>;
const nav=[["jouer","Jouer",Gamepad2],["classement","Classement",Trophy],["amis","Amis",Users],["compte","Compte",UserRound],["boutique","Boutique",Coins]] as const;
const modeTabs=[["classée","Partie classée",Swords],["solo","Solo",Zap],["daily","Grille du jour",CalendarDays],["hebdo","Grille hebdo",Flame],["privée","Salon privé",Users]] as const;
function Sudoku({difficulty="Intermédiaire",competitive=false,title="Arène éclair",active=true,initialSeconds=0,initialMistakes=0,onSolved,onMistake,onProgress,replayable=true,onReady,readyBusy=false,puzzleOverride,challengeLabel="GRILLE HEBDOMADAIRE",race,storageKey,hintsAllowed,soloExperience=false,onConnect}:{difficulty?:Difficulty;competitive?:boolean;title?:string;active?:boolean;initialSeconds?:number;initialMistakes?:number;onSolved?:(grid:number[],elapsedSeconds:number,puzzle:number[])=>void|{xpGained:number}|null|Promise<void|{xpGained:number}|null>;onMistake?:(index:number,number:number,id:string,grid:number[])=>Promise<number>;onProgress?:(filled:number,grid:number[])=>void;replayable?:boolean;onReady?:()=>void;readyBusy?:boolean;puzzleOverride?:number[];challengeLabel?:string;race?:{meName:string;opponentName:string;opponentProgress:number;totalToFill?:number};storageKey?:string;hintsAllowed?:number;soloExperience?:boolean;onConnect?:()=>void}){
 const game=puzzles[difficulty];
 const[variant,setVariant]=useState(()=>({puzzle:game.puzzle,solution:game.solution}));
 const[ready,setReady]=useState(!!puzzleOverride);
 const puzzle=puzzleOverride??variant.puzzle;
 const overrideSolution=useMemo(()=>puzzleOverride?solveSudoku(puzzleOverride):null,[puzzleOverride]);
 const solution=overrideSolution??variant.solution;
 const[cells,setCells]=useState([...puzzle]),[selected,setSelected]=useState<number|null>(null),[noteMode,setNoteMode]=useState(false),[cellNotes,setCellNotes]=useState<Record<number,number[]>>({}),[seconds,setSeconds]=useState(initialSeconds),[done,setDone]=useState(false),[experience,setExperience]=useState<number|"saving"|"guest"|"error"|null>(null),[history,setHistory]=useState<{cells:number[];notes:Record<number,number[]>}[]>([]),[mistakes,setMistakes]=useState(initialMistakes),[hintsUsed,setHintsUsed]=useState(0),[pendingMistake,setPendingMistake]=useState<{index:number;number:number;id:string}|null>(null),[mistakeError,setMistakeError]=useState(false),[mistakeLoaded,setMistakeLoaded]=useState(!storageKey);
 const hintLimit=hintsAllowed??(race?1:competitive?0:3);
 useEffect(()=>{if(puzzleOverride)return;const first=nextSudokuVariant(game.puzzle,game.solution,game.puzzle);setVariant(first);setCells([...first.puzzle]);setReady(true)},[difficulty,puzzleOverride,game]);
 useEffect(()=>{if(!storageKey)return;const saved=Number(window.localStorage.getItem(storageKey));const savedHints=Number(window.localStorage.getItem(`${storageKey}:hints`));setMistakes(Number.isInteger(saved)?Math.max(0,Math.min(3,saved)):0);setHintsUsed(Number.isInteger(savedHints)?Math.max(0,Math.min(1,savedHints)):0);setMistakeLoaded(true)},[storageKey]);
 useEffect(()=>{if(done||!active||!ready||mistakes>=3)return;const t=setInterval(()=>setSeconds(v=>v+1),1000);return()=>clearInterval(t)},[done,active,ready,mistakes]);
 const confirmMistake=async(value:{index:number;number:number;id:string},grid=cells)=>{if(!onMistake)return;setMistakeError(false);try{const count=await onMistake(value.index,value.number,value.id,grid);setMistakes(count);setPendingMistake(null)}catch{setMistakeError(true)}};
 const input=(n:number,index=selected,forceValue=false)=>{if(!ready||!mistakeLoaded||!active||index===null||puzzle[index]||done||mistakes>=3||pendingMistake||cells[index]===n)return;setHistory(h=>[...h.slice(-39),{cells:[...cells],notes:{...cellNotes}}]);if(noteMode&&!competitive&&!forceValue){setCellNotes(prev=>({...prev,[index]:(prev[index]||[]).includes(n)?(prev[index]||[]).filter(x=>x!==n):[...(prev[index]||[]),n].sort()}));return}const c=[...cells];c[index]=n;setCells(c);setCellNotes(prev=>({...prev,[index]:[]}));onProgress?.(c.filter((value,i)=>value===solution[i]).length,c);if(n!==solution[index]){const count=mistakes+1;setMistakes(count);if(storageKey)window.localStorage.setItem(storageKey,String(count));if(onMistake){const value={index,number:n,id:crypto.randomUUID()};setPendingMistake(value);void confirmMistake(value,c)}return}if(c.every((v,i)=>v===solution[i])){setDone(true);if(soloExperience){setExperience("saving");void Promise.resolve().then(()=>onSolved?.(c,Math.max(1,seconds),puzzle)).then(result=>setExperience(result&&typeof result==="object"?result.xpGained:"guest")).catch(()=>setExperience("error"))}else onSolved?.(c,Math.max(1,seconds),puzzle)}};
 const erase=()=>{if(selected===null||puzzle[selected]||mistakes>=3||pendingMistake)return;setHistory(h=>[...h,{cells:[...cells],notes:{...cellNotes}}]);const c=[...cells];c[selected]=0;setCells(c);setCellNotes(p=>({...p,[selected]:[]}))};
 const undo=()=>{if(mistakes>=3||pendingMistake)return;const last=history.at(-1);if(!last)return;setCells(last.cells);setCellNotes(last.notes);setHistory(h=>h.slice(0,-1))};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key>="1"&&e.key<="9")input(Number(e.key));if(e.key==="Backspace"||e.key==="Delete")erase();if(e.key.toLowerCase()==="n"&&!competitive)setNoteMode(v=>!v);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z")undo()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)});
 const filled=cells.filter(Boolean).length,givens=puzzle.filter(Boolean).length,raceProgress=race?.totalToFill?cells.filter((v,i)=>!puzzle[i]&&v===solution[i]).length:filled,raceTotal=race?.totalToFill??81,time=`${String(Math.floor(seconds/60)).padStart(2,"0")}:${String(seconds%60).padStart(2,"0")}`,selectedValue=selected===null?0:cells[selected];
 const related=(i:number)=>selected!==null&&(i%9===selected%9||Math.floor(i/9)===Math.floor(selected/9)||(Math.floor(i/27)===Math.floor(selected/27)&&Math.floor((i%9)/3)===Math.floor((selected%9)/3)));
 const useHint=()=>{if(!ready||!mistakeLoaded||!active||done||mistakes>=3||pendingMistake||hintsUsed>=hintLimit)return;const i=cells.findIndex((v,j)=>!puzzle[j]&&v!==solution[j]);if(i<0)return;setHintsUsed(hintsUsed+1);if(storageKey)window.localStorage.setItem(`${storageKey}:hints`,String(hintsUsed+1));setSelected(i);input(solution[i],i,true)};
 const newGame=()=>{const next=nextSudokuVariant(game.puzzle,game.solution,puzzle);setVariant(next);setCells([...next.puzzle]);setSelected(null);setNoteMode(false);setCellNotes({});setMistakes(0);setHintsUsed(0);setSeconds(0);setDone(false);setExperience(null);setHistory([])};
 if(!ready)return <div className="game-card" role="status">Préparation d’une nouvelle grille {difficulty}…</div>;
 return <div className={`game-card ${!active?"weekly-gated":""} ${mistakes>=3?"lost":""}`}><div className="game-top"><div><span className="eyebrow">{hintsAllowed===0&&race?"PARTIE CLASSÉE":race?"PARTIE PRIVÉE":competitive?"DÉFI":"PARTIE NORMALE"} · {difficulty.toUpperCase()} · {variant.puzzle===game.puzzle?game.id:"nouvelle grille"}</span><h2>{title}</h2></div><div className="game-status"><div className="lives" role="status" aria-label={`${Math.max(0,3-mistakes)} ${3-mistakes===1?"vie restante":"vies restantes"} sur 3`}>{[0,1,2].map(i=><Heart key={i} className={i<3-mistakes?"full":"empty"} fill={i<3-mistakes?"currentColor":"none"}/>)}</div><div className="timer"><Timer/>{time}</div></div></div>
 {!active&&onReady&&<div className="ready-gate"><Flame/><span>{challengeLabel}</span><h3>À vous de jouer</h3><p>La grille restera masquée jusqu’au départ. Le chronomètre démarre dès que vous appuyez sur « Prêt ».</p><button onClick={onReady} disabled={readyBusy}>{readyBusy?"Démarrage…":"Je suis prêt"}</button><small>Une seule tentative jusqu’à la prochaine grille</small></div>}
 {race&&<div className="opponents"><span className="me"><i/>{race.meName} <b>{raceProgress}/{raceTotal}</b></span><div className="race"><em style={{width:`${raceProgress/raceTotal*100}%`}}/></div><span><i/>{race.opponentName} <b>{race.opponentProgress}/{raceTotal}</b></span></div>}
 <div className="sudoku" role="grid" aria-label={`Grille de Sudoku 9 par 9, niveau ${difficulty}`}>{Array.from({length:9},(_,row)=><div key={row} role="row" className={`sudoku-row ${row===2||row===5?"block-bottom":""}`}>{cells.slice(row*9,row*9+9).map((v,col)=>{const i=row*9+col,sameValue=selectedValue>0&&v===selectedValue,wrong=!!v&&!puzzle[i]&&v!==solution[i];return <button key={i} role="gridcell" aria-rowindex={row+1} aria-colindex={col+1} aria-selected={selected===i} aria-label={`Case ligne ${row+1}, colonne ${col+1}${v?`, chiffre ${v}${wrong?", incorrect":""}`:", vide"}`} disabled={mistakes>=3||!!pendingMistake} onClick={()=>active&&setSelected(i)} className={`${puzzle[i]?"given":"entered"} ${selected===i?"sel":""} ${related(i)?"line":""} ${sameValue?"same":""} ${wrong?"wrong":""}`}>{v||((cellNotes[i]?.length)?<span className="cell-notes">{[1,2,3,4,5,6,7,8,9].map(n=><i key={n}>{cellNotes[i].includes(n)?n:""}</i>)}</span>:"")}</button>})}</div>)}</div>
 <div className="keypad" aria-label="Clavier numérique">{[1,2,3,4,5,6,7,8,9].map(n=><button key={n} aria-label={`Placer le chiffre ${n}`} aria-pressed={selectedValue===n} disabled={mistakes>=3||!!pendingMistake} className={selectedValue===n?"active-number":""} onClick={()=>input(n)}>{n}</button>)}</div>
 <div className="game-actions"><button aria-label="Activer ou désactiver les notes" disabled={competitive||mistakes>=3||!!pendingMistake} onClick={()=>setNoteMode(!noteMode)} className={noteMode?"active":""}><Pencil/>Notes <small>N</small></button><button aria-label="Effacer la case sélectionnée" disabled={mistakes>=3||!!pendingMistake} onClick={erase}><Eraser/>Effacer</button><button aria-label="Annuler la dernière action" onClick={undo} disabled={!history.length||mistakes>=3||!!pendingMistake}><RotateCcw/>Annuler</button><button aria-label={`Afficher un indice, ${Math.max(0,hintLimit-hintsUsed)} restant${hintLimit-hintsUsed===1?"":"s"}`} disabled={!active||!mistakeLoaded||done||hintLimit===0||hintsUsed>=hintLimit||mistakes>=3||!!pendingMistake||!cells.some((v,i)=>!puzzle[i]&&v!==solution[i])} onClick={useHint}><Lightbulb/>Indice ({Math.max(0,hintLimit-hintsUsed)})</button>{replayable&&<button aria-label="Nouvelle grille" onClick={newGame}><RotateCcw/>Nouvelle grille</button>}</div>
 <div className="game-footer"><span>3 vies par grille · {hintLimit?`${hintLimit-hintsUsed} indice${hintLimit-hintsUsed===1?"":"s"} restant${hintLimit-hintsUsed===1?"":"s"}`:"Aides désactivées"}</span><span>Progression <b>{Math.round((filled-givens)/(81-givens)*100)}%</b></span><span className="fair"><ShieldCheck/>{competitive?"Mode compétitif":"Solution unique vérifiée"}</span></div>
 {mistakes>0&&mistakes<3&&<p className="grid-invalid" role="status">Chiffre incorrect. {3-mistakes} {3-mistakes===1?"vie restante":"vies restantes"}.</p>}
 {mistakeError&&pendingMistake&&<p className="grid-invalid" role="alert">Impossible d’enregistrer l’erreur. <button className="retry-mistake" onClick={()=>void confirmMistake(pendingMistake)}>Réessayer</button></p>}
 {mistakes>=3&&<div className="loss-result" role="status"><X/><h3>Grille perdue</h3><p>Tu as utilisé tes trois vies. Cette grille ne peut plus être terminée.</p>{replayable&&<button onClick={newGame}>Nouvelle grille</button>}</div>}
 {done&&<div className={`victory${typeof experience==="number"?" reward-ready":""}`}><Trophy/><h3>{soloExperience&&experience==="saving"?"Grille terminée !":"Victoire !"}</h3><p>Grille {difficulty} terminée en {time}</p>{soloExperience&&<div className="solo-xp" role="status" aria-live="polite">{typeof experience==="number"?<><span className="solo-xp-burst" aria-hidden="true">✦</span><strong key={experience}>+{experience} XP</strong><small>Expérience ajoutée à ton compte</small></>:experience==="saving"?<small>Enregistrement de ton expérience…</small>:experience==="guest"?<><small>Connecte-toi pour gagner de l’XP sur les prochaines grilles.</small>{onConnect&&<button className="solo-xp-connect" onClick={onConnect}>Se connecter</button>}</>:experience==="error"?<small>Résultat non enregistré : aucun XP ajouté.</small>:null}</div>}{replayable?<button onClick={newGame} disabled={soloExperience&&experience==="saving"}>Nouvelle grille</button>:<small>Enregistrement du temps…</small>}</div>}</div>
}
export default function Home(){
 const[view,setView]=useState<View>("jouer"),[mode,setMode]=useState("solo"),[mobile,setMobile]=useState(false),[toast,setToast]=useState(""),[me,setMe]=useState<{signedIn:boolean;isAdmin:boolean;displayName:string|null}>({signedIn:false,isAdmin:false,displayName:null}),[authOpen,setAuthOpen]=useState(false),[recovery,setRecovery]=useState(false),[recoveryStatus,setRecoveryStatus]=useState<"checking"|"ready"|"expired">("checking");
 const account=useAccount();
 const cosmetics=useCosmetics(account);
 useEffect(()=>{if(account.user&&(view==="compte"||view==="boutique"))void cosmetics.refresh()},[view,account.user?.id]);
 useEffect(()=>{document.body.classList.toggle("menu-open",mobile);return()=>document.body.classList.remove("menu-open")},[mobile]);
 useEffect(()=>{if(account.loading)return;let active=true;supabase.auth.getSession().then(({data})=>fetch("/api/me",{cache:"no-store",headers:data.session?{Authorization:`Bearer ${data.session.access_token}`}:{}})).then(response=>response.json() as Promise<{signedIn:boolean;isAdmin:boolean;displayName:string|null}>).then(value=>{if(active)setMe(value)}).catch(()=>{});return()=>{active=false}},[account.loading,account.user?.id]);
 useEffect(()=>{let active=true;const url=new URL(window.location.href);if(url.searchParams.get("reset")==="1"){setRecovery(true);setAuthOpen(true);if(url.searchParams.has("error")||new URLSearchParams(url.hash.slice(1)).has("error"))setRecoveryStatus("expired");else void supabase.auth.getSession().then(({data,error})=>{if(active)setRecoveryStatus(!error&&data.session?"ready":"expired")}).catch(()=>{if(active)setRecoveryStatus("expired")})}const{data}=supabase.auth.onAuthStateChange((event,session)=>{if(event==="PASSWORD_RECOVERY"&&session){setRecovery(true);setRecoveryStatus("ready");setAuthOpen(true)}});return()=>{active=false;data.subscription.unsubscribe()}},[]);
 useEffect(()=>{if(account.user&&!account.loading&&!account.profile?.username&&!recovery){const timer=setTimeout(()=>setAuthOpen(true),0);return()=>clearTimeout(timer)}},[account.user,account.loading,account.profile?.username,recovery]);
 const notify=(s:string)=>{setToast(s);setTimeout(()=>setToast(""),2400)},title=useMemo(()=>({jouer:"Centre de jeu",compte:"Mon compte",tournois:"Tournois",classement:"Classement mondial",amis:"Amis & défis",stats:"Mes statistiques",boutique:"Boutique cosmétique"}[view]),[view]);
 const activeTheme=gridThemes.find(t=>t.id===cosmetics.state?.themeId)??gridThemes[0];
 return <main className="shell" style={{"--grid-one":activeTheme.colors[0],"--grid-two":activeTheme.colors[1]} as CSSProperties}><aside id="main-menu" className={mobile?"side open":"side"}><div className="brand"><div className="brandmark">9</div><div>SUDOKU <b>CLASH</b></div><button className="close" aria-label="Fermer le menu" onClick={()=>setMobile(false)}><X/></button></div><nav>{nav.map(([id,label,I])=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setMobile(false)}}><I/><span>{label}</span></button>)}{me.isAdmin&&<a className="admin-link" href="/admin"><LockKeyhole/><span>Administration</span></a>}</nav><div className="season"><span>BÊTA PUBLIQUE</span><b>Comptes et salons en ligne</b><div><i style={{width:"100%"}}/></div><small>Progression enregistrée et protégée</small></div><button className="settings"><Settings/>Paramètres</button></aside><button className={mobile?"scrim show":"scrim"} aria-label="Fermer le menu" tabIndex={mobile?0:-1} onClick={()=>setMobile(false)}/>
 <section className="app"><header><button className="menub" aria-label="Ouvrir le menu" aria-expanded={mobile} aria-controls="main-menu" onClick={()=>setMobile(true)}><Menu/></button><div className="page-title"><span className="crumb">SUDOKU CLASH /</span><h1>{title}</h1></div><div className="header-actions"><AccountButton account={account} cosmetics={cosmetics} onAccount={()=>setView("compte")} onOpen={()=>setAuthOpen(true)}/></div></header><div className="content">
 {view==="jouer"&&<><section className="welcome"><div><span className="live"><i/>BÊTA PUBLIQUE · COMPTES RÉELS</span><h2>Prêt pour le prochain clash ?</h2><p>Joue en solo, trouve un duel classé ou crée un salon privé.</p></div><button className="rank-card beta-account home-account-button" onClick={()=>account.user?setView("compte"):setAuthOpen(true)} aria-label={account.user?"Voir mon compte et personnaliser mon avatar":"Se connecter au compte"}><PlayerAvatar avatarId={cosmetics.state?.avatarId} image={cosmetics.state?.customAvatar} frameId={cosmetics.state?.frameId} size="large" fallback={account.user?undefined:"?"}/><span className="home-account-text"><small>MON COMPTE · {account.user?`NIVEAU ${cosmetics.state?.level??1}`:"NON CONNECTÉ"}</small><b>{account.profile?.username||"Choisir mon avatar"}</b><span>{account.user?"Voir le profil et les cadres":"Se connecter pour personnaliser"}</span></span></button></section><div className="mode-tabs">{modeTabs.map(([id,label,I])=><button key={id} onClick={()=>setMode(id)} className={mode===id?"active":""}><I/>{label}{id==="hebdo"&&<small>+500</small>}</button>)}</div>
 {mode==="classée"?<RankedMatch account={account} openAuth={()=>setAuthOpen(true)} renderGame={(match,refresh)=><RankedGame match={match} refresh={refresh} account={account} />}/>:<ModePanel mode={mode} notify={notify} account={account} cosmetics={cosmetics} openAuth={()=>setAuthOpen(true)}/>}</>}
 {view==="compte"&&<AccountOverview account={account} cosmetics={cosmetics} notify={notify} openAuth={()=>setAuthOpen(true)}/>}
 {view==="tournois"&&<Tournaments notify={notify}/>} {view==="classement"&&<Leaderboard/>} {view==="amis"&&<RealFriends account={account} notify={notify} openAuth={()=>setAuthOpen(true)}/>} {view==="stats"&&<Stats/>} {view==="boutique"&&<Shop notify={notify} cosmetics={cosmetics} account={account} openAuth={()=>setAuthOpen(true)}/>}
 </div></section>{toast&&<div className="toast"><Check/>{toast}</div>}{authOpen&&<AuthDialog account={account} recovery={recovery} recoveryStatus={recoveryStatus} onRecovered={()=>{setRecovery(false);window.history.replaceState({},"",window.location.pathname);setAuthOpen(false);notify("Mot de passe mis à jour")}} onClose={()=>setAuthOpen(false)}/>}</main>
}

function formatTime(total:number){const safe=Math.max(0,Math.floor(total));const hours=Math.floor(safe/3600),minutes=Math.floor((safe%3600)/60),seconds=safe%60;return hours?`${String(hours).padStart(2,"0")}:${String(minutes).padStart(2,"0")}:${String(seconds).padStart(2,"0")}`:`${String(minutes).padStart(2,"0")}:${String(seconds).padStart(2,"0")}`}
function TimedChallenge({kind,openAuth}:{kind:"daily"|"weekly";openAuth:()=>void}){
 const[data,setData]=useState<ChallengeData|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[authRequired,setAuthRequired]=useState(false),[error,setError]=useState(""),[now,setNow]=useState(0),[pendingGrid,setPendingGrid]=useState<number[]|null>(null);
 const refreshInFlight=useRef(false),retryAt=useRef(0);
 const isDaily=kind==="daily",label=isDaily?"GRILLE DU JOUR":"GRILLE HEBDOMADAIRE",frequency=isDaily?"jour":"semaine";
 useEffect(()=>{let live=true;supabase.auth.getSession().then(({data:sessionData})=>fetch(`/api/${kind}`,{cache:"no-store",headers:sessionData.session?{Authorization:`Bearer ${sessionData.session.access_token}`}:{}})).then(async response=>{if(response.status===401){if(live)setAuthRequired(true);return null}if(!response.ok)throw new Error("challenge_load");return response.json() as Promise<ChallengeData>}).then(value=>{if(live&&value)setData(value)}).catch(()=>{if(live)setError(`La grille ${isDaily?"quotidienne":"hebdomadaire"} est momentanément indisponible.`)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[kind,isDaily]);
 useEffect(()=>{if(!data)return;const initial=setTimeout(()=>setNow(Date.now()),0),timer=setInterval(()=>setNow(Date.now()),1000);return()=>{clearTimeout(initial);clearInterval(timer)}},[data]);
 useEffect(()=>{if(!data||!now||now<new Date(data.nextAt).getTime()||refreshInFlight.current||now<retryAt.current)return;
  refreshInFlight.current=true;
  void supabase.auth.getSession().then(({data:sessionData})=>fetch(`/api/${kind}`,{cache:"no-store",headers:sessionData.session?{Authorization:`Bearer ${sessionData.session.access_token}`}:{}})).then(async response=>{if(!response.ok)throw new Error("refresh_failed");return response.json() as Promise<ChallengeData>}).then(value=>{setData(value);setPendingGrid(null);setError("");retryAt.current=0}).catch(()=>{setError("Nouvelle grille indisponible. Nouvelle tentative dans quelques secondes.");retryAt.current=Date.now()+5000}).finally(()=>{refreshInFlight.current=false});
 },[kind,data?.nextAt,now]);
 const request=async(action:"ready"|"complete",grid?:number[])=>{setBusy(true);setError("");try{const{data:sessionData}=await supabase.auth.getSession();const response=await fetch(`/api/${kind}`,{method:"POST",headers:{"Content-Type":"application/json",...(sessionData.session?{Authorization:`Bearer ${sessionData.session.access_token}`}:{})},body:JSON.stringify({action,grid})});if(response.status===401){setAuthRequired(true);return}if(!response.ok)throw new Error("challenge_save");setData(await response.json());setPendingGrid(null)}catch{setError("Impossible d’enregistrer la tentative. Vérifiez votre connexion puis réessayez.")}finally{setBusy(false)}};
 const reportMistake=async(index:number,number:number,mistakeId:string)=>{const{data:sessionData}=await supabase.auth.getSession();const response=await fetch(`/api/${kind}`,{method:"POST",headers:{"Content-Type":"application/json",...(sessionData.session?{Authorization:`Bearer ${sessionData.session.access_token}`}:{})},body:JSON.stringify({action:"mistake",index,number,mistakeId})});if(response.status===401){setAuthRequired(true);throw new Error("authentication_required")}if(!response.ok)throw new Error("mistake_save");const updated=await response.json() as ChallengeData;setData(updated);return updated.mistakes};
 const remaining=data&&now?Math.max(0,Math.ceil((new Date(data.nextAt).getTime()-now)/1000)):0;
 if(loading)return <div className="panel weekly-state"><Timer/><h2>Chargement de la grille…</h2></div>;
 if(authRequired)return <div className="panel weekly-state"><ShieldCheck/><span className="eyebrow">TENTATIVE PROTÉGÉE</span><h2>Connectez-vous avant de jouer</h2><p>Votre compte Sudoku Clash enregistre votre départ, votre temps et votre participation du {frequency}.</p><button className="primary" onClick={openAuth}>Se connecter ou créer un compte</button></div>;
 if(!data)return <div className="panel weekly-state error"><X/><h2>Grille indisponible</h2><p>{error}</p><button className="primary" onClick={()=>location.reload()}>Réessayer</button></div>;
 if(!now)return <div className="panel weekly-state"><Timer/><h2>Préparation de la grille…</h2></div>;
 if(now>=new Date(data.nextAt).getTime())return <div className="panel weekly-state"><Timer/><h2>Chargement de la nouvelle grille…</h2>{error&&<p>{error}</p>}</div>;
 if(data.status==="completed")return <div className="panel weekly-state weekly-complete"><Trophy/><span className="eyebrow">GRILLE TERMINÉE</span><h2>Votre temps : {formatTime(data.elapsedSeconds||0)}</h2><p>Votre tentative est enregistrée. Cette grille ne peut plus être rejouée.</p><div className="next-week"><span>Prochaine grille dans</span><b>{formatTime(remaining)}</b></div></div>;
 if(data.status==="failed")return <div className="panel weekly-state weekly-failed"><X/><span className="eyebrow">TENTATIVE TERMINÉE</span><h2>Trois erreurs : grille perdue</h2><p>Cette grille ne peut plus être terminée ni rejouée.</p><div className="next-week"><span>Nouvelle grille dans</span><b>{formatTime(remaining)}</b></div></div>;
 const initialSeconds=data.startedAt&&now?Math.max(0,Math.floor((now-new Date(data.startedAt).getTime())/1000)):0;
 return <div className="play-layout"><div><Sudoku key={`${kind}-${data.nextAt}-${data.startedAt||"ready"}`} difficulty={isDaily?"Facile":"Difficile"} puzzleOverride={data.puzzle} competitive title={`${data.title} — Défi ${isDaily?"quotidien":"hebdomadaire"}`} active={data.status==="in_progress"} initialSeconds={initialSeconds} initialMistakes={data.mistakes} onMistake={reportMistake} replayable={false} challengeLabel={label} onReady={()=>request("ready")} readyBusy={busy} onSolved={grid=>{setPendingGrid(grid);request("complete",grid)}}/>{error&&<div className="weekly-error">{error}<button onClick={()=>pendingGrid?request("complete",pendingGrid):request("ready")} disabled={busy}>Réessayer</button></div>}</div><aside className="card rightcol weekly-rules"><span className="eyebrow">RÈGLES DU DÉFI</span><h3>Un {frequency}, une chance</h3><p>La grille apparaît au clic sur « Je suis prêt ». Le chronomètre continue même si vous fermez la page.</p><p>Trois erreurs mettent fin à la tentative.</p><div className="next-week compact"><span>Nouvelle grille dans</span><b>{formatTime(remaining)}</b></div><span className="fair"><ShieldCheck/>Départ et résultat vérifiés</span></aside></div>;
}
function ModePanel({mode,notify,account,cosmetics,openAuth}:{mode:string;notify:(s:string)=>void;account:ReturnType<typeof useAccount>;cosmetics:ReturnType<typeof useCosmetics>;openAuth:()=>void}){
 const[chosen,setChosen]=useState<Difficulty|null>(null);
 if(mode==="solo")return chosen?<div><div className="solo-bar"><button onClick={()=>setChosen(null)}>← Changer de difficulté</button><b>{chosen}</b><span>Grille valide · solution unique</span></div><Sudoku key={chosen} difficulty={chosen} title="Entraînement solo" soloExperience onConnect={openAuth} onSolved={async(grid,elapsedSeconds,puzzle)=>{if(!account.user)return null;const{data}=await supabase.auth.getSession();const response=await fetch("/api/account",{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${data.session?.access_token??""}`},body:JSON.stringify({difficulty:chosen,elapsedSeconds,puzzle,grid})});if(!response.ok)throw new Error("save_failed");const result=await response.json() as {xpGained:number};void cosmetics.refresh();return result}}/></div>:<div className="panel"><div className="panel-head"><span className="eyebrow">ENTRAÎNEMENT</span><h2>Choisis ta difficulté</h2><p className="panel-copy">Chaque niveau utilise une grille 9×9 validée et une difficulté fondée sur les techniques nécessaires pour la résoudre.</p></div><div className="difficulty-grid">{(["Débutant","Facile","Intermédiaire","Difficile","Expert","Maître"] as Difficulty[]).map((d,i)=><button onClick={()=>{setChosen(d);notify(`Grille ${d} chargée`)}} key={d}><span>{["🌱","●","◆","▲","⬢","♛"][i]}</span><b>{d}</b><small>{["Nus simples","Candidats uniques","Paires et blocs","Techniques avancées","Chaînes logiques","Logique extrême"][i]}</small></button>)}</div></div>;
 if(mode==="daily")return <TimedChallenge kind="daily" openAuth={openAuth}/>;
 if(mode==="hebdo")return <TimedChallenge kind="weekly" openAuth={openAuth}/>;
 return <PrivateLobby account={account} notify={notify} openAuth={openAuth} onRace={(room,players)=><RealRoomGame room={room} players={players} account={account} notify={notify}/>}/>
}

function RankedGame({match,refresh,account}:{match:RankedState;refresh:()=>Promise<void>;account:ReturnType<typeof useAccount>}){
 const[error,setError]=useState(""),[pendingGrid,setPendingGrid]=useState<number[]|null>(null);
 const puzzle=useMemo(()=>match.puzzle?.split("").map(Number)??[],[match.puzzle]);
 const complete=async(grid:number[])=>{setPendingGrid(grid);try{await rankedRequest("complete",{grid});setError("");setPendingGrid(null);await refresh()}catch{setError("Impossible d’enregistrer le résultat. Réessaie.")}};
 const mistake=async(index:number,number:number,mistakeId:string,grid:number[])=>{const result=await rankedRequest("mistake",{index,number,mistakeId,grid});await refresh();return result.mistakes??0};
 const update=(_filled:number,grid:number[])=>{void rankedRequest("progress",{grid}).catch(()=>{})};
 return <div className="ranked-game"><div className="solo-bar"><b>{match.rank?.label??"Partie classée"} · Grille {match.difficulty}</b><span>Adversaire trouvé : {match.opponentName}</span></div><Sudoku key={match.id} difficulty={match.difficulty??"Intermédiaire"} puzzleOverride={puzzle} competitive title="Duel classé 1 contre 1" active={match.status==="playing"} initialSeconds={Math.max(0,Math.floor((Date.now()-(match.startedAt??Date.now()))/1000))} initialMistakes={match.mistakes??0} replayable={false} hintsAllowed={0} onProgress={update} onMistake={mistake} onSolved={grid=>void complete(grid)} race={{meName:account.profile?.username||"Vous",opponentName:match.opponentName??"Adversaire",opponentProgress:match.opponentProgress??0,totalToFill:match.totalToFill}}/>{error&&<div className="weekly-error" role="alert">{error}{pendingGrid&&<button onClick={()=>void complete(pendingGrid)}>Réessayer</button>}</div>}</div>;
}

function RealRoomGame({room,players,account,notify}:{room:Room;players:RoomPlayer[];account:ReturnType<typeof useAccount>;notify:(s:string)=>void}){
 const me=players.find(player=>player.user_id===account.user?.id),opponent=players.find(player=>player.user_id!==account.user?.id);
 const[now]=useState(()=>Date.now()),startMs=room.started_at?new Date(room.started_at).getTime():now,initialSeconds=Math.max(0,Math.floor((now-startMs)/1000));
 const update=(filled:number)=>{void supabase.rpc("update_room_progress",{p_room_id:room.id,p_progress:filled})};
 const complete=async(grid:number[])=>{const{data,error}=await supabase.rpc("complete_room",{p_room_id:room.id,p_grid:grid.join("")});if(error)notify(error.message);else notify(`Grille validée en ${formatTime(Math.floor(Number(data)/1000))}`)};
 return <div><div className="solo-bar"><b>Salon {room.code}</b><span>{room.status==="finished"?"Course terminée":"Course en direct"}</span></div><Sudoku key={room.id} difficulty="Intermédiaire" puzzleOverride={room.puzzle.split("").map(Number)} competitive title="Course privée 1 contre 1" active={room.status==="playing"} initialSeconds={initialSeconds} replayable={false} storageKey={`sudoku-clash-room-lives:${room.id}:${account.user?.id}`} onProgress={update} onSolved={complete} race={{meName:account.profile?.username||"Vous",opponentName:opponent?.profile?.username||"Adversaire",opponentProgress:opponent?.progress||0}}/>{room.status==="finished"&&<div className="panel race-result"><Trophy/><h3>{room.winner_id===account.user?.id?"Victoire !":"Course terminée"}</h3><p>{me?.elapsed_ms?`Votre temps : ${formatTime(Math.floor(me.elapsed_ms/1000))}`:"Résultat enregistré"}</p></div>}</div>
}
function Tournaments({notify}:{notify:(s:string)=>void}){return <div><div className="feature-tourney"><div><span className="live"><i/>INSCRIPTIONS OUVERTES</span><h2>Open Arena #42</h2><p>64 joueurs · Élimination directe · Expert</p><div><b>20 000 <small>Sudokoins</small></b><span>Début dans 02:14:32</span></div><button onClick={()=>notify("Inscription confirmée à l’Open Arena #42")}><Trophy/>S’inscrire au tournoi</button></div><Crown/></div><div className="cards3">{[["Sprint du mercredi","32 joueurs","Intermédiaire","Ce soir · 20:00"],["Masters nocturne","128 joueurs","Maître","Vendredi · 22:00"],["Coupe des clubs","Équipes de 4","Avancé","Dimanche · 15:00"]].map(t=><article className="card" key={t[0]}><Trophy/><h3>{t[0]}</h3><p>{t[1]} · {t[2]}</p><b>{t[3]}</b><button onClick={()=>notify(`Inscription confirmée : ${t[0]}`)}>Voir le tournoi</button></article>)}</div></div>}
function Leaderboard(){
 type Row={position:number;username:string;points:number;wins:number;losses:number;rank:{label:string}};
 const[players,setPlayers]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(false);
 useEffect(()=>{let live=true;fetch("/api/ranked?leaderboard=1",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("classement");return r.json() as Promise<{players:Row[]}>}).then(data=>{if(live)setPlayers(data.players)}).catch(()=>{if(live)setError(true)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[]);
 return <div className="panel"><div className="panel-head"><span className="eyebrow">PARTIES CLASSÉES</span><h2>Classement Sudoku Clash</h2><p className="panel-copy">Les 100 meilleurs joueurs par points. Le rang Maître exige au moins 1 700 points et une place dans ce top 100.</p></div>{loading?<p>Chargement du classement…</p>:error?<p>Classement momentanément indisponible.</p>:players.length?<><div className="podium">{players.slice(0,3).map((r,i)=><div className={`pod p${i+1}`} key={r.position}><div>{i===0?<Crown/>:i+1}</div><b>{r.username}</b><span>{r.rank.label}</span><strong>{r.points} points</strong></div>)}</div><div className="rank-table"><div className="tr head"><span>Place</span><span>Joueur</span><span>Rang</span><span>Points</span><span>Victoires</span></div>{players.map(r=><div className="tr" key={r.position}><b>#{r.position}</b><span><i className="avatar small">{r.username.slice(0,2).toUpperCase()}</i>{r.username}</span><span>{r.rank.label}</span><strong>{r.points}</strong><span>{r.wins}</span></div>)}</div></>:<p>Le classement s’affichera dès les premières parties classées.</p>}</div>;
}
function Stats(){return <div><div className="stat-grid">{[["1 842","MMR actuel","+84 cette semaine"],["71%","Victoires","142 sur 200 parties"],["08:42","Temps moyen","Intermédiaire"],["18","Série record","7 actuellement"]].map(s=><div className="stat card" key={s[1]}><span>{s[1]}</span><b>{s[0]}</b><small>{s[2]}</small></div>)}</div><div className="stats-layout"><div className="panel"><h3>Progression MMR</h3><div className="chart">{[28,35,31,44,47,55,52,63,67,75,72,82].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><div className="axis"><span>S1</span><span>S2</span><span>S3</span><span>S4</span></div></div><div className="panel achievements"><h3>Succès récents</h3>{[["⚡","Éclair","Une grille en moins de 5 min"],["🔥","Inarrêtable","10 victoires consécutives"],["♛","Expert","100 grilles difficiles"]].map(a=><div key={a[1]}><span>{a[0]}</span><p><b>{a[1]}</b><small>{a[2]}</small></p><em>+250</em></div>)}</div></div></div>}
function Shop({notify,cosmetics,account,openAuth}:{notify:(value:string)=>void;cosmetics:ReturnType<typeof useCosmetics>;account:ReturnType<typeof useAccount>;openAuth:()=>void}){
 const[tab,setTab]=useState<"themes"|"avatars">("themes"),[busy,setBusy]=useState("");
 const data=cosmetics.state;
 const choose=async(id:string)=>{if(!data)return;setBusy(id);try{const owned=data.ownedThemes.includes(id);await cosmetics.action(owned?"equip_theme":"buy_theme",id);if(!owned)await cosmetics.action("equip_theme",id);notify(owned?"Fond équipé":"Fond débloqué et équipé")}catch(e){notify(e instanceof Error&&e.message==="not_enough_coins"?"Pas assez de Sudokoins":"Opération indisponible. Réessaie.")}finally{setBusy("")}};
 return <div><div className="shop-hero"><div><span className="eyebrow">PERSONNALISATION ÉQUITABLE</span><h2>Ton style. Zéro avantage.</h2><p>Tous les éléments de la boutique sont uniquement cosmétiques.</p></div><div><Coins/><span>TON SOLDE</span><b>{data?.coins.toLocaleString("fr-FR")??"—"}</b><small>SUDOKOINS</small></div></div><div className="shop-tabs"><button className={tab==="themes"?"active":""} onClick={()=>setTab("themes")}>Fonds de grille</button><button className={tab==="avatars"?"active":""} onClick={()=>setTab("avatars")}>Avatars</button></div>{tab==="avatars"?<AvatarShop cosmetics={cosmetics} account={account} notify={notify} openAuth={openAuth}/>:!account.user?<div className="panel cosmetic-closet"><p>Connecte-toi pour enregistrer tes fonds de grille.</p><button className="primary" onClick={openAuth}>Se connecter</button></div>:!data?<div className="panel cosmetic-closet">Chargement de la boutique…</div>:<div className="shop-grid">{gridThemes.map(t=><article className="product" key={t.id}><div className="theme-preview" style={{background:`radial-gradient(circle at 20% 20%,${t.colors[0]}55,transparent 40%),linear-gradient(135deg,#081021,${t.colors[1]}55)`}}><div>{Array.from({length:25}).map((_,i)=><i key={i}/>)}</div>{data.themeId===t.id&&<span>ÉQUIPÉ</span>}</div><h3>{t.name}</h3><button disabled={!!busy||(!data.ownedThemes.includes(t.id)&&data.coins<t.price)} onClick={()=>void choose(t.id)} className={data.ownedThemes.includes(t.id)?"owned":""}>{data.ownedThemes.includes(t.id)?data.themeId===t.id?"Équipé":"Équiper":<><Coins/>{t.price.toLocaleString("fr-FR")}</>}</button></article>)}</div>}</div>
}
