// Rebuilds lib/puzzle-bank.ts: `npm run puzzles:generate [perDifficulty] [seed] [difficulty]`.
import { writeFileSync } from "node:fs";
import { soloDifficulties, type Difficulty } from "../lib/difficulties";
import { puzzleBank } from "../lib/puzzle-bank";
import {
  carvePuzzle,
  classifyPuzzle,
  difficultyProfiles,
  randomSolution,
  seededRandom,
} from "../lib/sudoku-generator";

const perDifficulty = Number(process.argv[2] ?? 100);
const seed = Number(process.argv[3] ?? 20260926);
const only = process.argv[4] as Difficulty | undefined;
if (only && !soloDifficulties.includes(only)) throw new Error(`Unknown difficulty: ${only}`);
const random = seededRandom(seed);
const bank = Object.fromEntries(soloDifficulties.map((d) => [
  d,
  new Set(only ? puzzleBank[d].filter((p) => d !== only || classifyPuzzle(p.split("").map(Number)) === d) : []),
])) as Record<
  Difficulty,
  Set<string>
>;
const missing = () => soloDifficulties.filter((d) => (!only || d === only) && bank[d].size < perDifficulty);

let attempts = 0;
while (missing().length) {
  attempts++;
  // Aim at a difficulty that still needs puzzles; the grader decides where it really lands.
  const wanted = missing()[attempts % missing().length];
  const [low, high] = difficultyProfiles[wanted].clues;
  const target = low + Math.floor(random() * (high - low + 1));
  const puzzle = carvePuzzle(randomSolution(random), target, random);
  const difficulty = classifyPuzzle(puzzle);
  if (difficulty && (!only || difficulty === only) && bank[difficulty].size < perDifficulty)
    bank[difficulty].add(puzzle.join(""));
  if (attempts % 500 === 0)
    console.log(attempts, soloDifficulties.map((d) => `${d}:${bank[d].size}`).join(" "));
}

const body = soloDifficulties
  .map(
    (d) => `  ${JSON.stringify(d)}: [\n${[...bank[d]].map((p) => `    "${p}",`).join("\n")}\n  ],`,
  )
  .join("\n");
writeFileSync(
  new URL("../lib/puzzle-bank.ts", import.meta.url),
  `// Generated by scripts/generate-puzzle-bank.ts (seed ${seed}${only ? `; refreshed ${only}` : ""}); do not edit by hand.
// Server-only: importing it in the browser would reveal every puzzle.
import type { Difficulty } from "@/lib/difficulties";

export const puzzleBank: Record<Difficulty, readonly string[]> = {
${body}
};
`,
);
console.log(`done after ${attempts} attempts`);
