// Rebuilds lib/variant-bank.ts: `pnpm variants:generate [perVariant] [seed]`.
import { writeFileSync } from "node:fs";
import { seededRandom } from "../lib/sudoku-generator";
import { carveVariant, makeCages, randomVariantSolution } from "../lib/variant-generator";
import { cagesToText, geometryOf, variantIds, type VariantId } from "../lib/variants";

const perVariant = Number(process.argv[2] ?? 30);
const seed = Number(process.argv[3] ?? 20260930);
const random = seededRandom(seed);
// Clues left in each grid: enough to be fair, few enough to need real reasoning.
const clues: Record<VariantId, number> = { mini: 14, diagonal: 27, killer: 8 };

type Entry = { puzzle: string; solution: string; cages?: string };
const bank = {} as Record<VariantId, Entry[]>;
for (const id of variantIds) {
  const entries = new Map<string, Entry>();
  while (entries.size < perVariant) {
    const base = geometryOf(id);
    const solution = randomVariantSolution(base, random);
    const cages = id === "killer" ? makeCages(base.size, solution, random) : [];
    const geometry = geometryOf(id, cages);
    const puzzle = carveVariant(geometry, solution, clues[id], random);
    entries.set(puzzle.join(""), {
      puzzle: puzzle.join(""),
      solution: solution.join(""),
      ...(cages.length ? { cages: cagesToText(cages) } : {}),
    });
  }
  bank[id] = [...entries.values()];
  console.log(id, bank[id].length);
}

writeFileSync(
  new URL("../lib/variant-bank.ts", import.meta.url),
  `// Generated by scripts/generate-variant-bank.ts (seed ${seed}); do not edit by hand.
// Server-only: importing it in the browser would reveal every solution.
import type { VariantId } from "./variants";

export type VariantEntry = { puzzle: string; solution: string; cages?: string };

export const variantBank: Record<VariantId, readonly VariantEntry[]> = ${JSON.stringify(bank, null, 2)};
`,
);
